### PR TITLE
Addition of Member Count Display

### PR DESCRIPTION
**Pull request by AlMashreqi**
This will display the member count in the member-x channel, The Background is not cool, as i suck at designing.
It requires Canvas Lib. :)

### CODE REVIEW

**Comment by andrejarrell** [comment]
@sauoodwani 
When adding packages you can install them with `npm i packagename` and it will add that to `package.json` and `package-lock.json`. Would you be able to add the `canvas` package?

**Comment by sauoodwani** [comment]
> @sauoodwani
> When adding packages you can install them with `npm i packagename` and it will add that to `package.json` and `package-lock.json`. Would you be able to add the `canvas` package?

**Comment by AlMashreqi** [comment]
@andrejarrell 
Trash Why it doesn't even ask when closing the pull request, npm i know how to use but where should i do it ? in the workspace?

**Comment by andrejarrell** [comment]
@sauoodwani yes

**Comment by AlMashreqi** [comment]
My Keyboard is betraying meeeeeee, Andre Please Check the if it has been added ;-;

**Comment by andrejarrell** [comment]
@jmsaylor @sauoodwani  It's ready for merge.

**Pull request merged**
